### ISSUE TITLE
RemoteIP Install

### ISSUE THREAD

**Issue by Leykis** [engintron/engintron#216]
Hello,

We are having some issues installing mod_remoteip on our CloudLinux server. We have attempted to remove and reinstall Engintron a few times with no luck.

The only file that was installed regarding mod_remoteip is : /usr/local/src/engintron/apache/mod_remoteip.c

Anyway to install this manually?

Thank you.

**Comment by jcmdln** [comment]
According to the README.md, appears that this should be included by default?

```
Install mod_remoteip using the source file provided from the Engintron repo on GitHub. Many installations previously dealt with failed downloads of that file from the official Apache code repo, which resulted in mod_remoteip not being installed at all and thus Nginx could not pass the visitor's IP back to Apache.
```

https://github.com/engintron/engintron/blob/f5d06561ab50dee748a836418983556b0d6f03d8/README.md#changelog

**Comment by fevangelou** [comment]
Ask your hosting company to install the "httpd dev tools" package in your
OS which is a typical requirement to install custom Apache modules.

**Comment by Leykis** [comment]
Dev tools are installed.

**Comment by fevangelou** [comment]
Then consult your hosting company again as to why the mod_remoteip Apache
module can't be installed on your server. I'm out of ideas unfortunately...

**Comment by fevangelou** [comment]
Please let us know if you get this resolved with your hosting company.

**Comment by Leykis** [comment]
This was resolved after switching to Apache 2.4, as mod_remoteIP is not supported in Apache 2.2.

**Comment by fevangelou** [comment]
Engintron installs mod_rpaf for Apache 2.2 (which is pretty old btw).
mod_remoteip is incompatible with 2.2 for the record.

**Comment by Leykis** [comment]
It appears awstats is still showing the server IP instead of the visitor's IP. Anything we can check to investigate why this is not working?

**Comment by jerrybopara** [comment]
If you still getting Server Ip instead of Visitor's IP, I'd like to suggest  you to find out and check  "remoteip.conf" file and see if your Server's local Ip's are there. If not then you can add them manually.

On my server this file is located here - /usr/local/apache/conf/includes/remoteip.conf
# RemoteIP
LoadModule remoteip_module modules/mod_remoteip.so
RemoteIPInternalProxy 127.0.0.1 127.0.0.1 172.18.44.66
RemoteIPHeader X-Real-IP

Now you please try to change Apache log Format as below .  
LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

notes - please comment  the previous (combined) log format and add new one.
after restarting Apache , you will start getting Visitor's Ip in websites access.log.

these above settings  working for me very well, i hope that will works for you as well..
Thanks Jerry !!

**Comment by Leykis** [comment]
Hey Jerry. Thanks for the info. 

Tried that out and it unfortunately didn't change anything.

I can confirm Apache access logs show the correct visitor IP, it seems to related to Awstats.

**Comment by fevangelou** [comment]
Let's try this @Leykis ...

Open Apache's httpd.conf file and replace any occurrence of:
`%h %l %u`

with
`%a %l %u`

Then execute this as root via terminal (one line at a time):
```
/usr/local/cpanel/bin/apache_conf_distiller --update 
/scripts/rebuildhttpdconf 
/scripts/restartsrv httpd
```

Finally restart both Apache and Nginx.

Check your AWStats reports and let me know.

**Comment by ailyroot** [comment]
just want to add that we also have issues with awstats
CentOS7+cloudlinux+cagefs+mod_lsapi+latest engintron
please kindly fix this issue with awstats if you could

many thanks for nice mod

**Comment by ailyroot** [comment]
to add that , I see real ip showing up on cpanel  on centos6 by "default"
not sure why centOS7 is not

**Comment by mgilank** [comment]
Hi, actually, how to check if remoteip have forwarding visitor ip? is that on /var/log/nginx/access.log or in /etc/httpd/logs/access_log ?  because i got nothing in httpd log.
thanks

**Comment by fevangelou** [comment]
Nginx passes the visitor IP to Apache just fine. There is no problem here.
IPs are logged in both servers.

The issue is with AWStats and how it reads the Apache logs.

**Comment by mgilank** [comment]
Then the remoteip is not work or not forwarding, i got server ip in all logs in apache access.log and error.log
i have follow your step above, nothing work.

**Comment by ailyroot** [comment]
not working on our "two" newly installed CentOS7+cloudlinux +Cagefs+mod_lsapi

it will show like below on WHM 's apache status and it is "not" related to awstats
http://imgur.com/aXCvhuJ
showing only server ip

**Comment by mgilank** [comment]
Exactly the same as yours. My system on centos 6 cpanel + cloudlinux.
Modsecurity also get server ip.

**Comment by ailyroot** [comment]
we got another server which is

CentOS7+cloudilnux+cpanel+cagefs+mod_lsapi

BUT engitron is still 1.6.1, showing real visitors' ip fine

**Comment by fevangelou** [comment]
Both please re-install Engintron (via its WHM app). The related Apache 
may had not been properly configured.

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by mgilank** [comment]
Nice, update it to v1.7.2 and now all ip is forwarding. Whats the issue?
hope i can make some donation here.
Thanks!

**Comment by fevangelou** [comment]
Like I said, perhaps mod_remoteip was not properly installed. @mgilank if you wish to contribute to Engintron's development, you may consider getting a premium support package when that launches in the coming months :)

**Comment by fevangelou** [comment]
By popular demand https://engintron.com/?donate :)

**Comment by Leykis** [comment]
I have tried all the recommendations provided, and awstats and other things are still showing the server IP.

Any other options?

Thank you.

**Comment by fevangelou** [comment]
I can understand AWStats may have issues getting the right IP. But what "other things" are you referring to?

**Comment by Leykis** [comment]
Such as the Apache logs. Specifically in WHM under "Apache Status", as @ailyroot mentioned [above](https://github.com/engintron/engintron/issues/216#issuecomment-243456880). Screenshot : http://i.imgur.com/aXCvhuJ.jpg

**Comment by SashRaven** [comment]
To fix this issue engintron should do this by it self:

_Open Apache's httpd.conf file and replace any occurrence of:
%h %l %u
with
%a %l %u_

This is in such string:
sed -i "s:LogFormat \"%h %l:LogFormat \"%h %a %l:" 

After fixing log format web.stat begin work correctly.

**Comment by Leykis** [comment]
Happy to confirm that the modification of the log format in httpd.conf does actually resolve the issue.

The issue is _'/usr/local/cpanel/bin/apache_conf_distiller --update'_ does not seem to be saving the configuration, which causes it to be reverted when httpd.conf is rebuilt.

**Comment by fevangelou** [comment]
@sashraven if you look at the installer you'll notice Engintron correctly changes the Apache log format. The issue with AWStats (only) stems from the order of the log variables. Instead of "%h %a %l..." perhaps it should be "%a %h %l...". I'll test further and update the installer accordingly.

@leykis the changes must be distilled first. See how the Engintron installer does it.

**Comment by Leykis** [comment]
@fevangelou I have checked this and it's the same commands provided earlier. Rebuilding the httpd.conf is reverting the LogFormat changes even after being distilled. Will be reaching out to cPanel.

**Comment by Leykis** [comment]
According to cPanel, to customize the LogFormat directive you have to use a vhost.local configuration file : https://documentation.cpanel.net/display/EA/Custom+Templates

**Comment by andreioss** [comment]
Hey guys, I've discovered some problem, on the last engintrone with server CL7+cpanel(v58)+EA4, new server ip addresses have not added to /etc/apache2/conf.modules.d/360_mod_remoteip.conf automatically. 
Could someone help me understand, how it was added before (with EA3) to /etc/httpd/conf/includes/remoteip.conf ?

**Comment by fevangelou** [comment]
Reinstall and see if it gets fixed.

**Comment by andreioss** [comment]
I carefully read /engintron.sh, and saw there only simple steps to install mod_realip and generating config for it with current system ips, so I don't see any helpful changes in reinstall engintrone...
So I want to understand mechanism of this, as i think, adding new ips to /etc/apache2/conf.modules.d/360_mod_remoteip.conf is up to cpanel, as it understand that such module was installed, and it's native to it.

**Comment by Leykis** [comment]
Will be closing this as the actual Remote IP is resolved for me. I suggest opening a new issue if you are encountering any trouble still.

**Comment by fevangelou** [comment]
@andreioss Sometimes the installation of the actual Apache module may fail. Re-installing can fix this. As @Leykis wisely mentioned, it's best to open a new ticket if you still have issues with this.
