### ISSUE TITLE
Bug Report: chkserv wrong apache port?

### ISSUE THREAD

**Issue by rflack1717** [engintron/engintron#496]
I've noticed that in the following file, the httpd process is being monitored on port 80:

```/etc/chkserv.d/httpd```

Surely this is incorrect, as Apache/httpd has been moved to port 8080 with nginx on port 80, and this should be updated to reflect the new port? Oddly, if I update this file manually and then restart tailwatchd/chkservd, the port is set back to 80 once more. Further investigation suggests that cPanel cannot monitor Apache on a non-default port in this manner:

https://forums.cpanel.net/threads/chkserv-d-cant-change-default-httpd-port.114701/

It looks as if the solution is to create a new service monitor for Apache on the new port, and disabling the built-in monitoring for apache on port 80.

**Comment by bdtech** [comment]
I would think this would work out of the box. CP has a setting for alternative apache port which is what engintron overrides to grab 80 for nginx.

Home »Server Configuration »Tweak Settings Apache non-SSL IP/port

**Comment by rflack1717** [comment]
I think you've misunderstood the bug report entirely. The Apache port is fine and setup correctly, but the chkserv monitoring is invalid. Because default cPanel chkserv will only check the default "httpd" service on port 80, this means that if nginx fails, chkserv will instead attempt to restart httpd and not nginx - resulting in a constant cycle of restarts.

The default service monitoring needs to be disabled and a new httpd monitoring service set up for port 8080, with a new one for nginx also created for port 80. If not done, then the restart commands are wrong for each service.

**Comment by bdtech** [comment]
I understand the bug report entirely. CP makes the functionality to provide an alternative port, and the alternate port is found in the config file. Therefore it should carry over to chkserv.

I've created an hourly cron for time being to ensure the port:8080 is correct in /etc/chkserv.d/httpd

**Comment by rflack1717** [comment]
No, you haven't understood at all :) Your assumption that it "should carry over to chkserv" is wrong. Read the link I posted above, even cPanel support say that it doesn't carry over at all and a new service needs to be created.

Your cron is not a fix to this issue and is a poor workaround.

**Comment by bdtech** [comment]
If CP admits its an issue, then its a bug. They support having an alternate apache port - its a baseline functionality setting. Therefore it should be fixed by CP.

**Comment by rflack1717** [comment]
No, this should be fixed by engintron as it's a third party modification and it needs to ensure it sets itself up correctly for monitoring the services it is adding.

**Comment by bdtech** [comment]
Engintron does not create /etc/chkserv.d/httpd - its managed by CP which allows an alternate port.

**Comment by rflack1717** [comment]
Yes, but since engintron modifies the default port it needs to ensure that the monitoring also carries over to this new port. Since cPanel provide a very easy method to do this, Engintron needs to utilise the methods available to it and not just assume things that are completely incorrect.

I'm not sure why you're pushing the blame back to cPanel here when this is very easily fixed.

**Comment by bdtech** [comment]
Because the issue would still occur if you were running Engintron or not (httpd on an alternate port).

**Comment by rflack1717** [comment]
Your logic is nonsensical. If you were manually running httpd on an alternate port, you would manually make the changes necessary to ensure the monitoring was on the correct alternate port. Since engintron is responsible for this, it's also responsible for ensuring the appropriate monitoring changes are made.

**Comment by bdtech** [comment]
You wouldn't be manually running it on an alternate port. Its a CP feature built-in.

By creating an additional chkserv.d/httpd for 8080 your drifting from baseline CP and you will have to maintain any changes to how it monitors or restarts apache. Higher risk.

**Comment by rflack1717** [comment]
Now you're just contradicting yourself and not making any sense at all.

You're right, you wouldn't be manually running on it an alternate port, because port 80 is the default - which is exactly why chkserv is (by default) only configured to monitor on port 80. If you make any changes outside of this, you also need to manually correct the monitoring service. This is why engintron has to resolve the problem.

> By creating an additional chkserv.d/httpd for 8080 your drifting from baseline CP and you will have to maintain any changes to how it monitors or restarts apache. Higher risk.

No kidding! Running engintron is "drifting from baseline CP" so again your logic is nonsensical! Since engintron is modifying the "baseline CP" it also needs to modify the monitoring to accompany the services it is changing. This isn't difficult to grasp, so I'm not sure why you're being so obtuse.

**Comment by fevangelou** [comment]
If the port changed from some cPanel update, it means cPanel changed it. This means it's a cPanel bug, as it SHOULD respect the Apache port set in Tweak Settings.

Another user reported a log when cPanel killed Nginx during an update. Again, cPanel should check which port Apache binds to and not kill port 80 if Apache doesn't bind to it.

**Comment by fevangelou** [comment]
cPanel responded with this: https://twitter.com/engintron_sh/status/846684658335133696

> I recall us recently fixing something like that. Definitely we’ll take a look at it for them, though.
