### ISSUE TITLE
restart needed after autoSSL

### ISSUE THREAD

**Issue by jrsarath** [engintron/engintron#662]
I'm having an issue with AutoSSL
whenever a website gets a ssl certificate via AutoSSL
we need to restart Nginx either website shows OLD ssl certificate,
its kinda weird, we tried to update /etc/crontab , opened that file from WHM > Eningtron APP, clicked on save
still no result searched old issues for Hour didn't found any solution

**Comment by damianetienne** [comment]
Same here. I have the same trouble on my servers. 

I've to restart nginx every time that an autossl certificate is installed/renewed. I thought that the v1.8.4 version resolved that, but this is not the case.

**Comment by jrsarath** [comment]
Waiting for a solution...

**Comment by josephsimony** [comment]
Strangely I don't have now and didn't have any problems on any of my servers with Auto SSL and Engintron so far (not with SSL, not with their renewals).

Currently, servers running on:
Autossl provider: Let’s Encrypt
cPanel: 68.0.6
Engintron: 1.8.6

**Comment by damianetienne** [comment]
My case is with autossl with Comodo certs. I've not tried with LE.

**Comment by jrsarath** [comment]
@damianetienne i agree with you
we are using Comodo cert too
and problem exists

**Comment by Silviu-LS** [comment]
I have the same issues on 100+ servers , I had to create a bash scripts to read the SSL files if they were changed or newly created.

nginx reload instead of restart is working sometimes...

**Comment by jrsarath** [comment]
well we will love to take a look at that script 
thanks in advance

**Comment by jrsarath** [comment]
Where is author 
Hello, Author will look into this, please ?
this guy has this same issue over 100 server OMG !!
Engintron is a great Script for sure, but kindly try to resolve this please

**Comment by Silviu-LS** [comment]
This is still in progress , but I have attached it.

[ng.txt](https://github.com/engintron/engintron/files/1397635/ng.txt)

**Comment by jrsarath** [comment]
alright thank you,
and let's see if we can make any progress with your current work

**Comment by Silviu-LS** [comment]
Unfortunately , I don't have time atm to perfect the code in order to work as expected ( near perfect ) , but if you make any changes to the code , please share it back.

**Comment by jrsarath** [comment]
i will make sure that if we can make progress with your script then it be available as a patch for Engintron

**Comment by brixly** [comment]
My comments were added to  

#631 Need to restart nginx/apache everytime ssl certificate changes

Desperately in need of a solution / fix. 

I know that it's been referenced several times to say it should work as is, but it just doesn't for us. Almost every day we receive numerous requests to restart nginx.

**Comment by jrsarath** [comment]
i am sure that this is not a problem of cron job cron job is running,
I'm looking for something else 
https://github.com/tgerov/engintron/blob/patch-1/nginx/utilities/https_vhosts.sh
gonna try this patch

**Comment by brixly** [comment]
What are the differences between the patch you just referenced and the included version?

I can see it does a restart - I guess this is instead of the reload?

I always feel concerned when it comes to full nginx restarts incase of syntax errors which prevents nginx starting back up

**Comment by jrsarath** [comment]
yep, just a restart, while job can be done with a Reload

**Comment by brixly** [comment]
Can you test the patch on your system after reissuing a new SSL and let us know how it goes?

I assume the patch will work, but with the added risk of a full restart taking place rather than just a reload.

**Comment by Silviu-LS** [comment]
I'm guessing this will not work for current certificates , since the Patch doesn't check if the SSL file was updated ( cPanel SSL or Let's Encrypt ) , those are the issues that I have faced.

This will work for new SSL certificates , but the current ones ? that expires after 3 months and renewed monthly or at a custom date ?

**Comment by damianetienne** [comment]
@Silviu-LS Comodo and LE renew the certs every 3 months.

In my case, i need to restart nginx wether is a new certifiate or is just an extension of the current cert.

**Comment by Silviu-LS** [comment]
@damianetienne exactly what I need too.

I'm still trying to fix the final script to cover all this and reload the nginx when this is really needed.

**Comment by jrsarath** [comment]
I'm not sure if this php script is being executed or not, 
/etc/nginx/utilities/https_vhosts.php

**Comment by fevangelou** [comment]
@jrsarath Verify first you're not dealing with this https://github.com/engintron/engintron/wiki/SSL-certificate-changes-not-visible-in-Nginx%3F-Here's-a-possible-explanation-&-solution - also make sure it's not a case of CPANEL-15961 (bug).

**Comment by brixly** [comment]
@fevangelou my comments were added to

#631 Need to restart nginx/apache everytime ssl certificate changes

We have tried numerous times running this manually - the process completes fine for us, however it doesn't make a difference in terms of the SSL / browser situation. They aren't working in a browser until we run...

/engintron.sh purgecache

Actually, we tend to do the following...

/scripts/rebuildhttpdconf
/engintron.sh purgecache

We run the first to ensure the apache conf is correct / latest version - we then run the purgecache to, well, clear the caches and restart those services.

Once the services have been restarted, the SSL's work beautifully in the browser, every time.

If just the /etc/nginx/utilities/https_vhosts.php script is ran, it honestly makes no difference to the SSL as it appears in the browser.

We have known numerous times after 24 hours of a customer waiting post SSL installation a ticket being opened to point the issue out. We follow our own steps above, and its working again.

**Comment by fevangelou** [comment]
@brixly Nginx's purge cache option is actually kicked in by `bash /usr/local/src/engintron/engintron.sh purgecache` (line 18 in https_vhosts.sh). Caches will be properly flushed and Apache restarted. By issuing `/scripts/rebuildhttpdconf` you actually tell Apache to regenerate its httpd.conf file. There's no reason to do this. The https_vhosts.sh already kicked in EXACTLY because it detected a change in httpd.conf. Re-generating httpd.conf once more will simply force https_vhosts.sh to kick in again in 15 seconds. In other words, you're forcing your server to restart every 15 seconds. Think about it.

I have pushed a new build today which allows setting the Nginx vhost generation interval to something bigger than 15 seconds. This may come handy for servers with hundreds of sites for which the process to generate Nginx vhosts may take more than the actual interval for checking httpd.conf, which in turn could lead to a broken Nginx config.

Update to today's build and then open up the file /etc/nginx/utilities/https_vhosts.sh and change the value INTERVAL from 15 to say 20 or 30. Verify changes take effect using a private window in your browser.

**Comment by jrsarath** [comment]
i will update and will notify  @fevangelou 
and i have already verified this  https://github.com/engintron/engintron/wiki/SSL-certificate-changes-not-visible-in-Nginx%3F-Here's-a-possible-explanation-&-solution 
i can also make sure that cron is running and https_vhost.sh is being executed

**Comment by jhawkins002** [comment]
Been experiencing this problem for quite some time too; commented on other threads. Given the new release we tried today removing our CRON rules that automatically restart NGINX every 5 minutes to test if the new patches solved the issue on our servers. 

Unfortunately I can confirm we at least still have the problem. Tested with both 30 second and 60 second intervals. 

I can add that it seems the script is kicking off as it should because newly created/updated domains are indeed detected by https_vhosts.sh and updates are applied to the NGINX default_https.conf file. NGINX simply doesnt seem to be applying the new conf until a restart is manually invoked. 

I do think @fevangelou's idea that there is a timing element to this is potentially right on the money. During our test this afternoon, our logs show the following:

**Test account created at 14:28:41**

`Tue Oct 31 14:28:41 2017:CREATE:betatest:root:engin2.betatesting.as.ua.edu:67.43.4.132:engin2betatestin`

**LetsEncrypt Certificate installed at 14:29:45 (zulu-adjusted time)**

` [2017-10-31T19:29:41Z] The website “engin2.betatesting.as.ua.edu”, owned by “engin2betatestin”, has a faulty SSL certificate (OPENSSL_VERIFY:0:18:DEPTH_ZERO_SELF_SIGNED_CERT). AutoSSL will attempt to replace this certificate.`
`[2017-10-31T19:29:41Z] The system will attempt to renew SSL certificates for the following websites:`
`[2017-10-31T19:29:41Z]  engin2.betatesting.as.ua.edu (engin2.betatesting.as.ua.edu www.engin2.betatesting.as.ua.edu mail.engin2.betatesting.as.ua.edu)`
`[2017-10-31T19:29:45Z] The system has installed a new certificate onto “engin2betatestin”’s website “engin2.betatesting.as.ua.edu”.`

**Engintron sees an updated configuration in Apache and rebuilds the NGINX default_https.conf accordingly at 14:29:01 - note above that AutoSSL doesn't actually complete until 14:29:45 so the initiating element may be the account creation and not the certificate install**

```
stat /etc/nginx/conf.d/default_https.conf
  File: ‘/etc/nginx/conf.d/default_https.conf’
  Size: 53157     	Blocks: 104        IO Block: 4096   regular file
Device: fd03h/64771d	Inode: 1044384     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-10-31 14:35:42.126000000 -0500
Modify: 2017-10-31 14:29:01.686000000 -0500
Change: 2017-10-31 14:29:01.686000000 -0500
 Birth: -
```

**After the configuration update, /var/log/messages show that NGINX was never restarted to pick up an updated conf profile, as the last restart was at 14:23:34 (a restart we manually-invoked during a prior test)**

`Oct 31 14:23:34 galactica systemd: Started nginx - high performance web server.`

Hope this helps at least a little!

**Comment by jrsarath** [comment]
yeah actually i forgot to report back,
problem still persists

**Comment by pnboy** [comment]
it seams the problem is with /etc/nginx/utilities/https_vhosts.sh
the line:
RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php)

should probably be changed to something like:
RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?)

**Comment by jhawkins002** [comment]
Can confirm @pnboy's adjustment to https_vhosts.sh appears to have fixed the issue on our servers!

**Comment by brixly** [comment]
Thats great news! 

@fevangelou do you think it would be possible for you to confirm the accuracy of the above and possibly add it to a release?

I have checked our logs - it also looks as though the restart / purgecache isn't running as nginx isn't restarted or reloaded at any point. From this I can only assume the above will fix the issue.

May do some testing! Fingers crossed!

**Comment by brixly** [comment]
@jhawkins002 @pnboy  - I have tried to implement the change but its still not working correctly for me.

Currently, the function within https_vhosts.sh contains the following...

`function generate_https_vhosts {
    if [ -f /etc/nginx/utilities/https_vhosts.php ]; then
#        RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php)
        RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?)
        if [[ $RUN_CHECK == 1 ]]; then
            bash /usr/local/src/engintron/engintron.sh purgecache
        fi
    fi
}`

I have recorded the entire testing session in the hope it helps us resolve the issue. In one terminal, I am recording the output of 'nginx' within var/log/messages so that you can see when a restart actually takes place. From my investigation, when running /etc/nginx/utilities/https_vhosts.sh manually it doesn't run the purgecache at all.

However, as I show in the video instantly following the /engintron.sh purgecache the SSL is working correctly.

@fevangelou I hope this helps confirm the issues we are seeing - sometimes these things can be difficult to explain in enough detail. Hopefully a video speaks a thousand words.

https://www.useloom.com/share/f0312e3a78154e2a9886538a6709a6c1

**Comment by Silviu-LS** [comment]
I have fixed it.

/etc/nginx/utilities/https_vhosts.sh
`
function generate_https_vhosts {
    if [ -f "/etc/nginx/utilities/https_vhosts.php" ]; then
        RUN_CHECK=$(/usr/bin/php -qc /dev/null /etc/nginx/utilities/https_vhosts.php)
        if [[ $RUN_CHECK == "YES" ]]; then
            # bash /usr/local/src/engintron/engintron.sh purgecache
            service nginx reload
        fi
    fi
}

/etc/nginx/utilities/https_vhosts.php
`
// Run the check
if(!file_exists(NGINX_DEFAULT_HTTPS_VHOST) || (file_exists(HTTPD_CONF) && is_readable(HTTPD_CONF) && (filemtime(HTTPD_CONF) + HTTPD_CONF_LAST_CHANGED) > time()))
{
        generate_https_vhosts();
        echo "YES";
        exit(1);
}
else
{
        echo "NO";
        exit(0);
}
`
`

**Comment by brixly** [comment]
I think @fevangelou had written the code so that the 'exit(1)' should be picked up by the RUN_CHECK

It does seem to be just picking up the 'echo' - which is why your change has worked correctly.

Just tested this on the standard version of the file (and your ammended version)

[root@charlie ~]# RUN_CHECK=$(/usr/bin/php -qc /dev/null /etc/nginx/utilities/https_vhosts.php)
[root@charlie ~]# echo $RUN_CHECK
No changes in Apache's vhosts configuration. HTTPS vhosts for Nginx unchanged.

The [IF] then checks if the above variable is '1' - this is never the case from what I see?

As such, this may well explain why the purgecache is never ran

**Comment by brixly** [comment]
Come to think of it, based on the above by far the easiest fix would be to change the following...

https_vhosts.php

// Run the check
if (!file_exists(NGINX_DEFAULT_HTTPS_VHOST) || (file_exists(HTTPD_CONF) && is_readable(HTTPD_CONF) && (filemtime(HTTPD_CONF) + HTTPD_CONF_LAST_CHANGED) > time())) {
    generate_https_vhosts();
    echo "HTTPS vhosts for Nginx re-created.\n";
    exit(1);
} else {
    echo "No changes in Apache's vhosts configuration. HTTPS vhosts for Nginx unchanged.\n";
    exit(0);
}

to...

// Run the check
if (!file_exists(NGINX_DEFAULT_HTTPS_VHOST) || (file_exists(HTTPD_CONF) && is_readable(HTTPD_CONF) && (filemtime(HTTPD_CONF) + HTTPD_CONF_LAST_CHANGED) > time())) {
    generate_https_vhosts();
    echo "1"; exit(1);
    exit(1);
} else {
    echo "0";
    exit(0);
}

This should work shouldn't it?

@fevangelou may not find it preferable though, as it is nice having the echo explaining the status.

The issue appears to be entirely based on the fact that the IF check compares the variable, which from my output above is incorrect. 

If it should compare the 'exit()' value instead, then I guess a change to the RUN_CHECK line = I am a PHP developer at heart though, so not entirely sure how that would be altered. 

Any comments anyone?

**Comment by brixly** [comment]
Sorry to be flooding this! Just tested this as much as possible!

RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?)
echo $RUN_CHECK

@pnboy you are a genius :) This does indeed return the correct value (1 or 0)

This is now working perfectly for us...

INTERVAL="30" # Interval in seconds, must not exceed 60 (seconds)
COUNTER="0"

function generate_https_vhosts {
    if [ -f /etc/nginx/utilities/https_vhosts.php ]; then
        #RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php)
        RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?)
        if [[ $RUN_CHECK == "1" ]]; then
            echo "purging"
            bash /usr/local/src/engintron/engintron.sh purgecache
        fi
    fi
}

while [ $COUNTER -lt 60 ]; do
    generate_https_vhosts
    sleep $INTERVAL
    COUNTER=$[$COUNTER+$INTERVAL]
done

exit 0

**Comment by brixly** [comment]
Giving up slightly - I have disabled the cron entirely for now.

[root@charlie ~]# RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?); echo $RUN_CHECK
1
[root@charlie ~]# RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?); echo $RUN_CHECK
1
[root@charlie ~]# RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?); echo $RUN_CHECK
0
[root@charlie ~]# RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?); echo $RUN_CHECK
0

The value is changing to 0 without the cron actually running - shouldn't this remain '1' until the https_vhosts.sh script has ran from cron?

**Comment by brixly** [comment]
Done some further digging - Think we are getting somewhere!

https://github.com/engintron/engintron/issues/607

This made for a good read - I was struggling to get my head around the logic as sometimes the script was working, sometimes it didn't restart nginx.

I think the situation is this - 

If a rebuildhttpdconf is called and within the 15 seconds (as set in define('HTTPD_CONF_LAST_CHANGED', 15)) the https_vhosts.sh script is called then it works perfectly.

If though, the rebuildhttpdconf happens, then 30 seconds later the cron kicks in, that change is no longer recognised and the purgecache is skipped entirely.

I have tried changing to 5 seconds and 30 seconds - 30 seconds works really well. 

@fevangelou - is there a reason this is set as low as 15 seconds? Would you mind explaining the logic?

**Comment by fevangelou** [comment]
I have a question here...

If my original script did not work as expected, Engintron would not function properly for anyone. I hope this is clear.

What you're facing is a problem with certain conditions:
- you have servers with hundreds of cPanel accounts on them
- your servers are not as powerful to hold so many accounts
- given the above points, operations like Apache rebuilding its config take longer than most cPanel servers with Nginx/Engintron on them and subsequently cause misbehaviour on Engintron's part while its rebuilding the Nginx HTTPS vhosts.

The solution to the above problems is simple if you don't wish to change/upgrade your server hardware or distribute cPanel accounts to more servers. Simply raise HTTPD_CONF_LAST_CHANGED to a value higher than 30 secs. Make it 60 so that it's executed once a minute. This way, when a single site is added or removed, the change is mirrored in Nginx in 1 min tops.

For the record, the shell script https_vhosts.sh controls the process, while https_vhosts.php is the process to generate the Nginx HTTPS vhost files. When the PHP script outputs 1, it means the vhosts files have been regenerated. Then the shell script sees this value and tells Nginx to purge its cache and restart along with Apache. It's just 0 & 1 being output by the PHP script and this value is picked up by the shell script to determine whether it will purge Nginx's cache and restart both Nginx and Apache. The PHP script could output "Yes Sir" and "No Sir". It doesn't matter as long as the shell script knows what to expect as a control value in order to do what it's supposed to do.

So the fact that you're seeing something "change" magically when you output "YES" or "NO" is NOT based on that change but rather the circumstances. That's why your change fails later. And by circumstances, I switch back to my initial point made: lots of cPanel accounts or poor performing servers. Of course it's a matter of WHEN the changes occur. If you, as the server admin, perform any code changes when there are no clients using their cPanel accounts, it's natural that you'll see "YES" and "NO" working instead of 1 and 0. They are both valid of course, but you're simply testing things out when the scripts did not have any issue in the first place.

Re-consider your strategy. Either distribute cPanel accounts to more poor performing servers (who would either way explode without Nginx) or simply upgrade your servers with the right components (e.g. RAM, which is dead simple to add).

**Comment by jhawkins002** [comment]
That may be true in some cases. 

I can report we have documented this issue occurring on a brand new cPanel server (Xeon E3, 4 core, 16GB RAM) with 0 other accounts than the one we used to test Engingtron and SSL. The server was also running on a recent release Engintron (i.e. the CRON format fix had been implemented). No other third party plugins or cPanel addons were installed at the time. 

The log data we provided above in this particular thread (showing NGINX never restarted) was from a staging server with ~ 60 accounts. It happens to be a Xeon E3 machine with 12GB that typically runs a load of 0.06 or so.

**Comment by fevangelou** [comment]
@jhawkins002 so you setup a stock cPanel server with Engintron on it and it had issues with vhost generation? On a valid and publicly accessible domain/subdomain? Without any other plugins or modifications in cPanel?

**Comment by jhawkins002** [comment]
Precisely. The actual NGINX https conf appears to generate just fine (timestamp verified by stat) after the domain gets its SSL certificate, but NGINX itself never restarts - verified in /var/log/messages

**Comment by fevangelou** [comment]
Is the shell script https_vhosts .sh executable? Did you run the installation as root user?

**Comment by jhawkins002** [comment]
Indeed.

```
[root@betatesting]# ls -l /etc/nginx/utilities/https_vhosts.sh
-rwxr-xr-x 1 root root 929 Nov  8 11:55 /etc/nginx/utilities/https_vhosts.sh
```

**Comment by fevangelou** [comment]
I can't reproduce your error. Sorry.

**Comment by brixly** [comment]
I can reproduce it - it's been the same for us but the blame is being pushed to the hardware. 

Our situation is identical.

**Comment by fevangelou** [comment]
Prove why. Because it's 2 users so far out of 40k using Engintron.

**Comment by brixly** [comment]
Although not many, I do see a few more people who have commented on this thread (as well as a number of similar related threads) - they / we are all having to try and add modifications and fixes to the system

**Comment by photogaff** [comment]
Add me to the list of people experiencing the error - The only way I could resolve my issue was to disable and re-enable Engintron - there may have been another way, but that was my initial 'fix quickly' solution because I was seeing SSL errors on all letsencrypt configured domains.

**Comment by pnboy** [comment]
Hi @fevangelou 
the main issue is in /etc/nginx/utilities/https_vhosts.sh

that scripts is counting on a 1 from the /etc/nginx/utilities/https_vhosts.php return value in the variable RUN_CHECK, to fire the purgecache, but this will never happen as it's the output of the script that is returned, the echo's, not the exit return value. This variable ends up with the content "HTTPS vhosts for Nginx re-created.\n"

For the script to work as intended it needs to be changed to something like:
RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php > /dev/null 2>&1 ; echo $?)

so that it actually get the return value of the command, not the output :)

**Comment by fevangelou** [comment]
@pnboy Good catch. Devised a bit differently overall, but you can see the changes in the just released v1.8.7.

**Comment by nuclearsam** [comment]
I am facing the exact same issue. The expired certificates are cached until I restart (or clear cache) manually. I have only a few sites (around 4) running on a very powerful hardware.

Since the status of this issue is closed, does that mean it is fixed in the next version update? or do we need to make any changes manually to fix this?

Regards
Sam

**Comment by brixly** [comment]
@nuclearsam - try and upgrade to the latest version of Engintron (1.8.7)

The new version released by @fevangelou seems to have resolved the issue for us. 

Check /etc/nginx/utilities/https_vhosts.log shortly after issuing a new SSL certificate - if the log has some contents, it will show the purgecache function running.

If nothing is being output to the logs, try going editing the cron via the Engintron interface, then re-saving the cron entry.

**Comment by pnboy** [comment]
@fevangelou it still seams not to work (for me), this is the output of RUN_CHECK:
```
<br /> <b>Warning</b>: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in <b>/etc/nginx/utilities/https_vhosts.php</b> on line <b>40</b><br /> 1
0
0
0

```

**Comment by brixly** [comment]
This isn't because of engintron - you need to set your timezone in php

**Comment by pnboy** [comment]
the command in /etc/nginx/utilities/https_vhosts.sh
`/usr/bin/php -c /dev/null -q /etc/nginx/utilities/https_vhosts.php ; echo $?`
overrides the php.ini timezone definition, so it has to be fixed in that engintron php script, either by suppressing the warning or by adding something similar to:
```
if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}
``` 

or by redirecting the output of the command to somewhere else

**Comment by imorandinwnp** [comment]
Hi. Still experiencing AutoSSL being "cached" here. Only way to solve it is reloading nginx (service nginx reload).
https_vhosts.sh script does not solve the problem.
Engintron version 1.8.7

I suggest adding a service nginx reload to https_vhosts.sh script

**Comment by valiant1x** [comment]
Issue still occurring in Engintron version 1.8.10, please reopen @jrsarath @brixly

**Comment by damianetienne** [comment]
Indeed.

One of the upper comments solves the problem but, after every update, seems that the updater overwrite the changes.

**Comment by fevangelou** [comment]
@damianetienne Which one?

@imorandinwnp Nginx is reloaded when its cache is purged. Look closer ;)

**Comment by jhawkins002** [comment]
Not sure if this adds to the discussion - but cPanel has FINALLY added official hooks for autossl events as of v.72. Hooray!

Changelog details: https://documentation.cpanel.net/display/72Docs/72+Release+Notes#id-72ReleaseNotes-NewStandardizedHooks
