### ISSUE TITLE
login to http[s]://cpanel.domain.tld never works on Safari for ipad or iphone or any mac

### ISSUE THREAD

**Issue by lpasquali** [engintron/engintron#993]
I understand that this is a very odd, wrong, insecure way to connect to a cpanel but some users here in the company I work for use:
http://cpanel.domain.tld

for some reason any IOS device like any recent iPad and iPhone do not login, and I'm represented tto the login page with no error, the url changes in:

http://cpanel.domain.tld/cpsess<and_other_stuff_like_usual_login_url_in_cpanel>

if I use http://cpanel.domain.tld:8080 it works fine.

I can reproduce it on any clean install of engintron with no custom_rules or any other modification to configuration.
I found this issue resolving the (both plain and ssl) http[s]://cpanel.domain.tld issue with webmail I posted in #965 and this is a separated issue only affecting mobile devices and tablets from Apple.
Plain cpanel login works both in http and https for any Windows, Linux desktop, or OSX.

**Comment by timmmmyboy** [comment]
I can reproduce this error (and #965) for us as well and it's a pretty big issue. We use the cpanel and webmail subdomains over https because we can't rely on non-standard ports being open for all customer ISPs and we were seeing both webmail broke as well as accessing cPanel on mobile devices. We have disabled Engintron on our servers until we can address this.

**Comment by lpasquali** [comment]
timmmmyboy be aware that vanilla engintron.sh is also bugged for disabling/enabling as I reported, you have to switch two seds between enable) and disable) stanzas in engintron.sh, iirc, I pulled a patch, check the pull requests.

**Comment by fevangelou** [comment]
@lpasquali What bug exactly?

**Comment by lpasquali** [comment]
@fevangelou #973 check the pull requests.....

**Comment by lpasquali** [comment]
FYI I went further on this topic (#993 )this bug is reproducible for any version of Safari both for http anf https both on any iOS or OSX.

**Comment by fevangelou** [comment]
Fixed in v1.9.3.

**Comment by lpasquali** [comment]
> Fixed in v1.9.3.
Sorry Fotis,
Do you mean you fixed #973? I see the sed are switched,  in the meanwhile I changed the title of this bug to make it more meaningful

**Comment by fevangelou** [comment]
Yes. For the cpanel/webmail subdomain I already gave you the solution on how to implement this in "custom rules".

**Comment by lpasquali** [comment]
nope, it is Safari related, your solution has been tested several times by me in test and production environments, it does not fix this issue.

**Comment by fevangelou** [comment]
This double proxying (Nginx to Apache and Apache to cPanel) causes certain issues obviously. If you can dig deeper and locate the issue (since you already have the environment set for that) I'll be more than happy to implement a fix for it.

**Comment by lpasquali** [comment]
I'm actively trying to get a successful login from Safari, oddly, cPanel released an app for iOS and it does work correctly

**Comment by ddrhost** [comment]
It would be interesting to look for a solution, because without Engintron the accesses work normally.

**Comment by fevangelou** [comment]
HTTP should redirect to HTTPS automatically.

**Comment by Simoneworks** [comment]
Hi @fevangelou we still have the issue on Safari, with Mac / ipad / iphone; many of our customers are opening tickets about this issue, so it really important to solve it for us .

Could you please try to find a solution about that?

We are available to work together to fix it, but we need your help. 

Let us know

**Comment by WhiteDogBe** [comment]
Just for information, this "issue" still exists today and is quite difficult to explain to end-users.
Wished there was a workaround and never understood why only Safari is affected.
The root cause is not with Engintron though. 

Luckily cPanel own nginx implementation seems to suffer from the same issue:
https://docs.cpanel.net/knowledge-base/third-party/nginx/

> Note:
> You cannot use the Safari® web browser to log in to a service subdomain. Use another browser, or log in with the service’s port URL.

So some hope they'll fix this on their end in a few months or years :)

**Comment by fevangelou** [comment]
@WhiteDogBe 🥇

**Comment by WhiteDogBe** [comment]
Sorry, I just can't let this go :)

I'm still intrigued at what the actual root cause of this problem is. My best guess at the moment is that it has to do with the cookies being sent with the port specified. Chrome doesn't seem bothered by this. No way to override that in engintron though, unless you add that lua module.

I also tried to proxy directly to port 2082 or 2083, bypassing Apache. This seemed to have no effect on this problem.

I do want to share the workaround I'm using at the moment. Not the pretiest but it lowers the number of "i can't logon" tickets. These lines send Apple users to the port and upgrade http to https. I also modify the "tweak settnigs" to disable the redirections cPanel itself tries to do, not sure if that's really needed.

```
# === REDIRECT CPANEL SUBDOMAINS TO PORT FOR SAFARI ===
if ($http_user_agent ~* "(iPhone|iPad|Safari)") { set $UseThePort "port"; } # only apply to Apple
if ($http_user_agent ~* "(Chrome|Edge|FireFox)") { set $UseThePort "noport"; } # to counter Chrome also having the Safari UA on macOS
if ($host ~* "^(webmail)\.") { set $RedirToPort "2096"; set $RedirToPortPlease "please"; }
if ($host ~* "^(cpanel)\.") { set $RedirToPort "2083"; set $RedirToPortPlease "please"; }
set $portRedirection $UseThePort$RedirToPortPlease;
if ($portRedirection = "portplease") { return 302 https://$host:$RedirToPort; }

# === REDIRECT CPANEL SUBDOMAINS TO HTTPS ===
if ($scheme = "http") { set $redirToSSL "secure"; }
if ($host ~* "^(webmail|cpanel|whm|webdisk|cpcalendars|cpcontacts)\.") { set $isWebmail "please"; }
set $httpsRedirection $redirToSSL$isWebmail;
if ($httpsRedirection = "secureplease") { return 301 https://$host$request_uri; }
```

**Comment by fevangelou** [comment]
Change:
```
if ($http_user_agent ~* "(iPhone|iPad|Safari)") { set $UseThePort "port"; } # only apply to Apple
if ($http_user_agent ~* "(Chrome|Edge|FireFox)") { set $UseThePort "noport"; } # to counter Chrome also having the Safari UA on macOS
```
to this:
```
set $UseThePort "noport";
if ($http_user_agent ~* "(iPhone|iPad|Safari)") { set $UseThePort "port"; } # only apply to Apple
```
In other words, override `$UseThePort` only for Apple devices.

**Comment by fevangelou** [comment]
Unless this DOES affect every browser that may use a different UA. In which case it's batshit crazy that this happens in cPanel...

**Comment by WhiteDogBe** [comment]
Hi,

That second line is needed because for example Chrome, on macOS, has the following user agent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36`

Where Safari has:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15`

Apparantly the 537.36 is some legacy stuff that is been going around.
But given the above, if I'd check only for "Safari" it will match with Chrome too on macOS.
That's why I added the second line which undoes the "Safari" detection when it's actually Chrome.
There are complex scripts out there to properly determine the browser but I wanted to keep it simple.

**Comment by lpasquali** [comment]
Hello all, 
As far as I remember the problem cant be handled on server side in any way, mainly because only for safari both on iOS and OSx headers are shipped different. Only way I did found was to rewrite needed vhost header with an nginx running LUA, but this adds the need of a bit more of ram in case you f many vhosts per machine. I think I could provide ways to implement this if interested.

Luca Pasquali
